# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias bbuu='brew update && brew upgrade'
alias all="argo logs @latest"
setopt clobber
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
autoload -Uz promptinit
promptinit
prompt powerlevel10k

# Created by `pipx` on 2022-10-29 23:16:30
export PATH="/Users/vts1/prj/bin:/opt/homebrew/Cellar/gnu-sed/4.9/libexec/gnubin:$PATH:/Users/vts1/.local/bin"
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"
#
#. <(minikube completion zsh)
. <(kubectl completion zsh)
. <(eksctl completion zsh)
alias k=kubectl
complete -o default -F __start_kubectl k
#
complete -C 'aws_completer' aws
autoload -Uz compinit && compinit
#if type brew &>/dev/null; then
#    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
#    autoload -Uz compinit >/dev/null 2>&1
#    compinit >/dev/null 2>&1
#fi
compdef _argo argo
source <(argo completion zsh)
. <(helm completion zsh)
. <(k9s completion zsh)
if type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export DIRENV_LOG_FORMAT=
eval "$(direnv hook zsh)"
source virtualenvwrapper.sh
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
